Сдаю ТЗ Спринт 10
FDRoosvelt/java-filmorate pull request #5
Opened 2023-01-24 20:25 UTC by FDRoosvelt

2023-01-25 18:28 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    User updateUser(User user);
Нужно реализовать удаление объектов
По ТЗ должны быть новые интерфейсы FilmStorage и UserStorage, в которых  определены методы добавления, удаления и модификации объектов.

2023-01-25 18:30 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private boolean releaseDateLogic(Film film) {
return !film.getReleaseDate().isBefore(LocalDate.of(1895, DECEMBER, 28)); - так проще

2023-01-25 18:33 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    UserStorage userStorage;
Контроллеры не должны ничего знать про хранилища. Смысл в том, что приложение делится на слои и эти слои слабо связаны между собой. 
Контроллер знает какой сервис вызвать, а сервис уже знает что использовать чтобы сохранить данные

2023-01-25 18:36 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userStorage.addUser(user);
Нужно добавить обработчик ошибки, которая возникает, когда передаются неверные данные
Сейчас приходит 500
{
	"error": "Произошла непредвиденная ошибка.",
	"description": "Validation failed for argument [0] in public ru.yandex.practicum.filmorate.model.User ru.yandex.practicum.filmorate.controller.UserController.addUser(ru.yandex.practicum.filmorate.model.User): [Field error in object 'user' on field 'email': rejected value [email3email.com]; codes [Email.user.email,Email.email,Email.java.lang.String,Email]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [user.email,email]; arguments []; default message [email],[Ljavax.validation.constraints.Pattern$Flag;@5ad271a2,.*]; default message [must be a well-formed email address]] "
}

На самом деле это не ошибка на стороне сервера, а ошибка на стороне клиента - он прислал неверные данные

2023-01-25 18:37 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film likeFilm(@PathVariable("id") long id,
Если есть желание, то добавь еще проверку входных данных
{
	"error": "Произошла непредвиденная ошибка.",
	"description": "Failed to convert value of type 'java.lang.String' to required type 'long'; nested exception is java.lang.NumberFormatException: For input string: \"aaa\""
}

2023-01-25 18:40 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        Throwable thrown = assertThrows(ValidationException.class, () -> {
Throwable thrown = assertThrows(ValidationException.class, () -> inMemoryFilmStorage.addFilm(film));
Тоже можно компактнее написать

2023-01-25 18:42 UTC, EvgenyKoptubenko requested changes
Работа сделана очень хорошо. Всего несколько предложений по улучшению кода

2023-01-26 10:43 UTC, FDRoosvelt commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return userStorage.addUser(user);
реализовал в коде, некоторые проверки, но постам не пропускает, требует код ошибки 404, хотя там явно ошибка валидации с кодом 400

2023-01-26 18:20 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-01-27 12:13 UTC, merged